D-02 Python Exercises
===========

## Basic Python

#### Exercise 1
Write a function `even` that takes as input a list of integers and returns a copy of the list where all the odd numbers have been removed.

In [1]:
def even(l):
    """Removes all odd numbers from the list l."""
    return [ i for i in l if i % 2 == 0]

Sample test:

In [2]:
even([1, 4, 9, 16, 25, 36, 49, 64, 81, 100]) == [4, 16, 36, 64, 100]

True

#### Exercise 2
Write a function `word_reverse` that takes as input a string consisting of separated words and returns a new string where each word has been reversed.

In [3]:
def word_reverse(s):
    """Reverses every word in the string s."""
    return ' '.join([ t[::-1] for t in s.split()])

Sample test case:

In [4]:
word_reverse('this might be the best course i have ever taken') == 'siht thgim eb eht tseb esruoc i evah reve nekat'

True

#### Exercise 3

Write a function `frequency` that takes as input a string and returns the letter frequency of the string as a list of integers where the $i$-th value corresponds to the frequency of the $i$-th letter in the English alphabet.

In [5]:
def frequency(s):
    """Computes the letter frequency of the string s."""
    l = [0]*26
    for c in s.lower():
        if c.isalpha():
            l[ord(c) - ord('a')] += 1
    return l

Sample test case:

In [6]:
frequency('this might be the best course i have ever taken') == [2, 2, 1, 0, 8, 0, 1, 4, 3, 0, 1, 0, 1, 1, 1, 0, 0, 2, 3, 5, 1, 2, 0, 0, 0, 0]

True

#### Exercise 4
Write a function `randword` that picks a random word from a list of words from the [SOWPODS](data/sowpods.txt) dictionary. This file is [Peter Norvig’s](https://en.wikipedia.org/wiki/Peter_Norvig) compilation of the dictionary of words used in professional Scrabble tournaments. Each line in the file contains a single word.

In [7]:
import random
def randword():
    """Returns a random word from the SOWPODS dictionary."""
    with open('sowpods.txt', 'r') as f:
        words = f.read().splitlines()
        return random.choice(words)
randword()

'THINNER'

Sample test case:

#### Exercise 5
Write a function `pref_count` that takes as input a string and outputs the number of words from the [SOWPODS](data/sowpods.txt) dictionary that have the string as a prefix.

In [8]:
def pref_count(s):
    """Returns the number of words in the SOWPOD dictionary that have s as a prefix."""
    with open('sowpods.txt', 'r') as f:
        words = f.read().splitlines()
        return len([w for w in words if w.startswith(s)])

In [9]:
pref_count('AB') == 866

True

## Numpy
Check [this out](http://www.scipy-lectures.org/) and please remember to [RDFM](https://docs.scipy.org/doc/numpy-dev/reference/index.html#reference) while solving these exercises.

#### Exercise 6
Import `numpy`.

In [10]:
import numpy as np

#### Exercise 7
Using `numpy`, write a function `rand2darr` that takes a single integer $n$ as input and returns a random $n \times n$ array and its minimum and maximum value. 

In [11]:
def rand2darr(n):
    """Returns a random nxn array and its minimum and maximum value."""
    a = np.random.randint(0, 100, (n, n))
    return a, np.min(a), np.max(a)

In [12]:
rand2darr(10)

(array([[15, 36, 85, 37, 47, 63, 91, 55, 68, 37],
        [85, 94, 81, 75, 17, 26, 38, 52, 82, 22],
        [ 4,  1, 46, 38, 89, 31, 62, 53, 77, 40],
        [22, 35, 52, 63, 98, 44, 43, 26, 99, 53],
        [62, 71, 45, 43, 96, 73, 58, 54, 19,  2],
        [69, 21, 29, 49, 54,  5, 45, 65, 80, 24],
        [95,  5, 40, 48, 46, 58, 23, 83, 40, 24],
        [92, 50, 27, 90,  2, 27, 34,  8, 53, 79],
        [38, 52, 24, 86, 40, 76, 14, 40, 31, 61],
        [99, 53, 11, 85, 42, 40, 47, 34, 23, 12]]), 1, 99)

#### Exercise 8
Using `numpy`, write a function `randarr` that takes as input two integers $n$ and $d$ and returns a random $n^d$ array and its mean value.

In [13]:
def randarr(n, d):
    """Returns a random n^d array and its mean value."""
    arr = np.random.randint(0, n**2, tuple([n for i in range(d)]))
    return (arr, arr.mean())

In [14]:
randarr(10, 3)

(array([[[84, 24, 74, 16, 34, 61, 79, 69, 28, 62],
         [83, 59,  6, 20, 14, 40, 72, 10, 25, 19],
         [43, 33, 85, 70, 19,  6, 95, 72,  0, 40],
         [18, 52, 89, 32, 95, 25, 87, 16, 51,  5],
         [ 2, 24, 83,  4, 91, 95, 33, 67,  7, 43],
         [36, 21, 43, 13, 54,  6, 73, 77, 87, 39],
         [ 3, 78, 94,  0, 69, 25,  0,  7, 40, 52],
         [66, 80, 32, 42, 84, 93, 94, 19, 67, 85],
         [67, 77, 71, 73, 86,  5, 39, 59, 34, 45],
         [46, 98, 88, 74, 47, 82, 11,  9, 45, 62]],
 
        [[89, 43, 12, 18, 56, 80, 95,  5, 27,  3],
         [63, 62, 90,  1, 54, 23, 16, 53, 23, 44],
         [98,  9, 71, 58, 40, 99, 30, 65, 76, 37],
         [89, 83,  1, 63, 57, 45, 71, 45, 23,  1],
         [22, 22, 36, 87, 26, 53, 63, 94, 33, 50],
         [95, 55, 73, 78, 21, 87, 62, 59, 75, 64],
         [52, 34, 73, 25, 55, 47,  9, 34, 78, 65],
         [88, 37, 14,  8, 58, 50, 93, 75, 37, 42],
         [42, 97, 74,  8, 51, 15, 10, 39, 13, 63],
         [27, 70, 61, 26, 70

#### Exercise 9
Using `numpy`, write a function `monthdates` that takes a single integer $m$ as input and returns an array with the dates of all the days of the $m$-th month of the current year.

In [15]:
def monthdates(m):
    """Returns an array with every days date in month m of the current year."""
    nextmonth = ((m + 1) % 13) + 1
    nextyear = 2018 if m == 12 else 2017
    print(np.datetime64("2017-{}-01".format(str(m).zfill(2))))
    return np.arange(np.datetime64("2017-{}-01".format(str(m).zfill(2))), np.datetime64("{}-{}-01".format(str(nextyear).zfill(2), str(nextmonth).zfill(2))))

In [16]:
import datetime

def monthdates(m):
    """Returns an array with every days date in month m of the current year."""
    today = datetime.datetime.now()
    nextMonthsYear = today.year
    startDate = datetime.date(nextMonthsYear, m, 1)
    
    if(m != 12):
        nextMonth = m + 1
    else:
        nextMonth = 1
        nextMonthsYear +=1
        
    endDate = datetime.date(nextMonthsYear, nextMonth, 1)
    return np.arange(startDate, endDate, dtype='datetime64[D]')  

In [17]:
monthdates(8)

array(['2018-08-01', '2018-08-02', '2018-08-03', '2018-08-04',
       '2018-08-05', '2018-08-06', '2018-08-07', '2018-08-08',
       '2018-08-09', '2018-08-10', '2018-08-11', '2018-08-12',
       '2018-08-13', '2018-08-14', '2018-08-15', '2018-08-16',
       '2018-08-17', '2018-08-18', '2018-08-19', '2018-08-20',
       '2018-08-21', '2018-08-22', '2018-08-23', '2018-08-24',
       '2018-08-25', '2018-08-26', '2018-08-27', '2018-08-28',
       '2018-08-29', '2018-08-30', '2018-08-31'], dtype='datetime64[D]')

#### Exercise 10
Using `numpy`, write a function `colsort` that takes as input a $2$-dimensional array and an integer $c$ and returns the array sorted by the $c$-th column. 

In [18]:
def colsort(m, c):
    """Returns the array 2-dimensional m sorted by the c-th column."""
    return m[np.argsort(m[:,c])]

In [19]:
arr = randarr(10, 2)
sortedarr = colsort(arr[0], 4)
print(sortedarr)

[[58 83 80 16 23 92 19 51 27 92]
 [48 24 31 13 28  6 87 21 29 14]
 [15 45 63 42 32 23  4 66 80 51]
 [43 77  7 97 52 32 71 40 66 59]
 [70  8 55 78 78 18 88 81 72 74]
 [67  8 11 44 79 87 44 71 89  4]
 [14 86 41 69 87 11 52 53  1 45]
 [76 35  7 93 87 31 65 25  1 13]
 [16 69 93 19 95 45 35 85 85 98]
 [ 9 21 10 30 98 60 17 91 95 41]]


#### Exercise 11
Using `numpy`, write a function `is_diagonal` that takes as input a $2$-dimensional array and checks if it is a diagonal matrix.

In [20]:
def is_diagonal(m):
    """Checks if the 2-dimensional array m is a diagonal matrix."""
    return np.all(np.equal(np.diag(np.diag(m)), m))

In [21]:
arr = np.diag(np.arange(0, 10))
print(arr)
is_diagonal(arr)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]


True

## Pandas
Please remember to [RDFM](http://pandas.pydata.org/pandas-docs/stable/) while solving these exercises.

#### Exercise 12


Import `pandas`.

In [22]:
import pandas as pd

#### Exercise 13
Read the csv document [`weather.csv`](data/weather.csv) into a dataframe and while doing so, use the first column as the index column and parse it properly at dates and add custom names to the columns.

In [23]:
weather = pd.read_csv('weather.csv', parse_dates=[0], index_col=0)

In [24]:
weather.head()

Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
Date/Time                                                        
2012-01-01 00:00:00      -1.8                -3.9           86   
2012-01-01 01:00:00      -1.8                -3.7           87   
2012-01-01 02:00:00      -1.8                -3.4           89   
2012-01-01 03:00:00      -1.5                -3.2           88   
2012-01-01 04:00:00      -1.5                -3.3           88   

                     Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)  \
Date/Time                                                                
2012-01-01 00:00:00                4              8.0           101.24   
2012-01-01 01:00:00                4              8.0           101.24   
2012-01-01 02:00:00                7              4.0           101.26   
2012-01-01 03:00:00                6              4.0           101.27   
2012-01-01 04:00:00                7              4.8           101.23   

                                  Weather  
Date/Time                                  
2012-01-01 00:00:00                   Fog  
2012-01-01 01:00:00                   Fog  
2012-01-01 02:00:00  Freezing Drizzle,Fog  
2012-01-01 03:00:00  Freezing Drizzle,Fog  
2012-01-01 04:00:00                   Fog

#### Exercise 14
Print the first 10 rows of the csv document.

In [25]:
weather.head(10)

Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
Date/Time                                                        
2012-01-01 00:00:00      -1.8                -3.9           86   
2012-01-01 01:00:00      -1.8                -3.7           87   
2012-01-01 02:00:00      -1.8                -3.4           89   
2012-01-01 03:00:00      -1.5                -3.2           88   
2012-01-01 04:00:00      -1.5                -3.3           88   
2012-01-01 05:00:00      -1.4                -3.3           87   
2012-01-01 06:00:00      -1.5                -3.1           89   
2012-01-01 07:00:00      -1.4                -3.6           85   
2012-01-01 08:00:00      -1.4                -3.6           85   
2012-01-01 09:00:00      -1.3                -3.1           88   

                     Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)  \
Date/Time                                                                
2012-01-01 00:00:00                4              8.0           101.24   
2012-01-01 01:00:00                4              8.0           101.24   
2012-01-01 02:00:00                7              4.0           101.26   
2012-01-01 03:00:00                6              4.0           101.27   
2012-01-01 04:00:00                7              4.8           101.23   
2012-01-01 05:00:00                9              6.4           101.27   
2012-01-01 06:00:00                7              6.4           101.29   
2012-01-01 07:00:00                7              8.0           101.26   
2012-01-01 08:00:00                9              8.0           101.23   
2012-01-01 09:00:00               15              4.0           101.20   

                                  Weather  
Date/Time                                  
2012-01-01 00:00:00                   Fog  
2012-01-01 01:00:00                   Fog  
2012-01-01 02:00:00  Freezing Drizzle,Fog  
2012-01-01 03:00:00  Freezing Drizzle,Fog  
2012-01-01 04:00:00                   Fog  
2012-01-01 05:00:00                   Fog  
2012-01-01 06:00:00                   Fog  
2012-01-01 07:00:00                   Fog  
2012-01-01 08:00:00                   Fog  
2012-01-01 09:00:00                   Fog

#### Exercise 15
Print the last 10 rows of the csv document.

#### Exercise 16
Print the dates and the weather descriptions of rows 300 to 320.

In [26]:
weather[300:321]['Weather'].size

21

#### Exercise 17
Print the temperature, wind speed and the weather column of the csv document, accompanied by the dates.

In [27]:
weather[['Temp (C)', 'Wind Spd (km/h)', 'Weather']]

Temp (C)  Wind Spd (km/h)               Weather
Date/Time                                                           
2012-01-01 00:00:00      -1.8                4                   Fog
2012-01-01 01:00:00      -1.8                4                   Fog
2012-01-01 02:00:00      -1.8                7  Freezing Drizzle,Fog
2012-01-01 03:00:00      -1.5                6  Freezing Drizzle,Fog
2012-01-01 04:00:00      -1.5                7                   Fog
2012-01-01 05:00:00      -1.4                9                   Fog
2012-01-01 06:00:00      -1.5                7                   Fog
2012-01-01 07:00:00      -1.4                7                   Fog
2012-01-01 08:00:00      -1.4                9                   Fog
2012-01-01 09:00:00      -1.3               15                   Fog
2012-01-01 10:00:00      -1.0                9                   Fog
2012-01-01 11:00:00      -0.5                7                   Fog
2012-01-01 12:00:00      -0.2                9                   Fog
2012-01-01 13:00:00       0.2               13                   Fog
2012-01-01 14:00:00       0.8               20                   Fog
2012-01-01 15:00:00       1.8               22                   Fog
2012-01-01 16:00:00       2.6               13         Mostly Cloudy
2012-01-01 17:00:00       3.0               13                Cloudy
2012-01-01 18:00:00       3.8               15                  Rain
2012-01-01 19:00:00       3.1               15                  Rain
2012-01-01 20:00:00       3.2               19                Cloudy
2012-01-01 21:00:00       4.0               20                Cloudy
2012-01-01 22:00:00       4.4               24          Rain Showers
2012-01-01 23:00:00       5.3               30                Cloudy
2012-01-02 00:00:00       5.2               35          Rain Showers
2012-01-02 01:00:00       4.6               39                Cloudy
2012-01-02 02:00:00       3.9               32         Mostly Cloudy
2012-01-02 03:00:00       3.7               33         Mostly Cloudy
2012-01-02 04:00:00       2.9               32         Mostly Cloudy
2012-01-02 05:00:00       2.6               32         Mostly Cloudy
...                       ...              ...                   ...
2012-12-30 18:00:00     -12.6               24          Mainly Clear
2012-12-30 19:00:00     -13.4               26          Mainly Clear
2012-12-30 20:00:00     -13.8               24                 Clear
2012-12-30 21:00:00     -13.8               20          Mainly Clear
2012-12-30 22:00:00     -13.7               19          Mainly Clear
2012-12-30 23:00:00     -12.1               28         Mostly Cloudy
2012-12-31 00:00:00     -11.1               26                Cloudy
2012-12-31 01:00:00     -10.7               15                Cloudy
2012-12-31 02:00:00     -10.1                9                Cloudy
2012-12-31 03:00:00     -11.8                6         Mostly Cloudy
2012-12-31 04:00:00     -10.5               11                Cloudy
2012-12-31 05:00:00     -10.2                6                Cloudy
2012-12-31 06:00:00      -9.7                4                Cloudy
2012-12-31 07:00:00      -9.3                0          Snow Showers
2012-12-31 08:00:00      -8.6                4          Snow Showers
2012-12-31 09:00:00      -8.1                4                  Snow
2012-12-31 10:00:00      -7.4                4              Snow,Fog
2012-12-31 11:00:00      -6.7                9                  Snow
2012-12-31 12:00:00      -5.8                4                  Snow
2012-12-31 13:00:00      -4.6                4                  Snow
2012-12-31 14:00:00      -3.4                6                  Snow
2012-12-31 15:00:00      -2.3                9                  Snow
2012-12-31 16:00:00      -1.4               13                  Snow
2012-12-31 17:00:00      -1.1               19                  Snow
2012-12-31 18:00:00      -1.3               17                  Snow
2012-12-31 19:00:00

#### Exercise 18
Output the rows of March only. 

In [28]:
weather[(weather.index > '2012-03-01') & (weather.index < '2012-04-01')]

Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
Date/Time                                                        
2012-03-01 01:00:00      -5.7                -8.7           79   
2012-03-01 02:00:00      -5.4                -8.3           80   
2012-03-01 03:00:00      -4.7                -7.7           79   
2012-03-01 04:00:00      -5.4                -7.8           83   
2012-03-01 05:00:00      -5.3                -7.9           82   
2012-03-01 06:00:00      -5.2                -7.8           82   
2012-03-01 07:00:00      -4.9                -7.4           83   
2012-03-01 08:00:00      -5.0                -7.5           83   
2012-03-01 09:00:00      -4.9                -7.5           82   
2012-03-01 10:00:00      -4.7                -7.3           82   
2012-03-01 11:00:00      -4.4                -6.8           83   
2012-03-01 12:00:00      -4.3                -6.8           83   
2012-03-01 13:00:00      -4.3                -6.9           82   
2012-03-01 14:00:00      -3.9                -6.6           81   
2012-03-01 15:00:00      -3.3                -6.2           80   
2012-03-01 16:00:00      -2.7                -5.7           80   
2012-03-01 17:00:00      -2.9                -5.9           80   
2012-03-01 18:00:00      -3.0                -6.0           80   
2012-03-01 19:00:00      -3.6                -6.4           81   
2012-03-01 20:00:00      -3.7                -6.4           81   
2012-03-01 21:00:00      -3.9                -6.7           81   
2012-03-01 22:00:00      -4.3                -6.9           82   
2012-03-01 23:00:00      -4.3                -7.1           81   
2012-03-02 00:00:00      -4.8                -7.3           83   
2012-03-02 01:00:00      -5.3                -7.9           82   
2012-03-02 02:00:00      -5.2                -7.8           82   
2012-03-02 03:00:00      -5.5                -7.9           83   
2012-03-02 04:00:00      -5.6                -8.2           82   
2012-03-02 05:00:00      -5.5                -8.3           81   
2012-03-02 06:00:00      -5.6                -8.6           79   
...                       ...                 ...          ...   
2012-03-30 18:00:00       3.9                -7.9           42   
2012-03-30 19:00:00       3.1                -6.7           49   
2012-03-30 20:00:00       3.0                -8.4           43   
2012-03-30 21:00:00       1.7                -9.0           45   
2012-03-30 22:00:00       0.4                -8.1           53   
2012-03-30 23:00:00       1.4                -7.7           51   
2012-03-31 00:00:00       1.5                -8.6           47   
2012-03-31 01:00:00       1.3                -9.6           44   
2012-03-31 02:00:00       1.3                -9.7           44   
2012-03-31 03:00:00       0.7                -8.8           49   
2012-03-31 04:00:00      -0.9                -8.5           56   
2012-03-31 05:00:00      -0.6                -9.2           52   
2012-03-31 06:00:00      -0.5                -9.2           52   
2012-03-31 07:00:00      -0.3                -9.2           51   
2012-03-31 08:00:00       0.7                -8.5           50   
2012-03-31 09:00:00       1.5                -7.8           50   
2012-03-31 10:00:00       2.9                -8.1           44   
2012-03-31 11:00:00       4.6                -9.7           35   
2012-03-31 12:00:00       6.4                -7.1           37   
2012-03-31 13:00:00       6.5                -9.7           30   
2012-03-31 14:00:00       7.7                -8.5           31   
2012-03-31 15:00:00       7.7                -8.6           30   
2012-03-31 16:00:00       8.4                -7.7           31   
2012-03-31 17:00:00       7.9                -8.1           31   
2012-03-31 18:00:00       7.0                -8.2           33   
2012-03-31 19:00:00       5.9                -8.0           36   
2012-03-31 20:00:00       4.4                -7.2           43   
2012-03-31 21:00:00       2.6                -6.3           5

#### Exercise 19
Output the average temperature of each day.

In [29]:
weather.groupby(pd.TimeGrouper(freq='D'))['Temp (C)'].mean()

Date/Time
2012-01-01     0.629167
2012-01-02     0.041667
2012-01-03   -14.416667
2012-01-04   -13.645833
2012-01-05    -6.750000
2012-01-06   -11.141667
2012-01-07    -5.012500
2012-01-08    -5.970833
2012-01-09    -4.295833
2012-01-10    -1.112500
2012-01-11   -12.358333
2012-01-12    -6.541667
2012-01-13    -4.600000
2012-01-14   -16.295833
2012-01-15   -18.983333
2012-01-16   -14.000000
2012-01-17    -5.858333
2012-01-18    -9.116667
2012-01-19   -10.170833
2012-01-20   -12.112500
2012-01-21   -14.833333
2012-01-22   -14.166667
2012-01-23    -2.800000
2012-01-24     2.583333
2012-01-25    -3.733333
2012-01-26    -6.229167
2012-01-27    -1.479167
2012-01-28     0.320833
2012-01-29    -0.900000
2012-01-30    -7.641667
                ...    
2012-12-02     3.058333
2012-12-03     3.958333
2012-12-04     7.841667
2012-12-05     2.729167
2012-12-06    -2.745833
2012-12-07     0.625000
2012-12-08     1.925000
2012-12-09    -0.808333
2012-12-10    -0.004167
2012-12-11    -5.950000
2012-1

#### Exercise 20
Output the average temperature of each month.

In [30]:
weather['Temp (C)'].groupby(pd.TimeGrouper(freq='M')).mean()

Date/Time
2012-01-31    -7.371505
2012-02-29    -4.225000
2012-03-31     3.121237
2012-04-30     7.009306
2012-05-31    16.237769
2012-06-30    20.134028
2012-07-31    22.790054
2012-08-31    22.279301
2012-09-30    16.484444
2012-10-31    10.954973
2012-11-30     0.931389
2012-12-31    -3.306317
Freq: M, Name: Temp (C), dtype: float64