# Basic Linear Algebra

Partly based on material from J.R. Johansson (jrjohansson at gmail.com)

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
from numpy import *

Vectorizing code is the key to writing efficient numerical calculation with Python/Numpy. That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

## Vectors and Matrices

Using NumPy we can define vectors and matrices with both real or complex elements. Although, in contrast to Matlab, where matrix is the default type, in Python we need to define vectors and matrices as `array` or `matrix` type from NumPy package.

<img  src="matrix.png"/>

In [2]:
a = array([10,20,30])   # Define a vector of size 3 using type 'array'
a.shape          # Size/shape of vector

(3,)

Note that Numpy also supports the `matrix` keyword. Numpy matrices are strictly 2-dimensional while Numpy arrays (ndarrays) are N-dimensional.

Numpy matrices provide a convenient notation for matrix multiplication ($A * B$), transpose, conjugate transpose and inverse.

In [3]:
b = matrix ('10 20 30')
b.shape

(1, 3)

### Euclidean norm

In [5]:
norm = linalg.norm(a)      # Euclidean norm of vector a
print('a =', a)
print('norm(a) =', norm)

x = a/linalg.norm(a)       # Make normalized/unit vector from a
print('x =', x)
print('norm(x) =', linalg.norm(x))

a = [10 20 30]
norm(a) = 37.4165738677
x = [ 0.26726124  0.53452248  0.80178373]
norm(x) = 1.0


### Transposition
Transposition of vectors requires you to ensure that Python knows whether you have a row or a colmn vector when you have a 1D array. For that you need to use `reshape` to shape the vector into a 2D array (as matrix of size $1 \times n$ or $n \times 1$.
Where transposition makes sense it can be obtained by attribute `.T`.

In [6]:
a.T  # Doesn't work!

array([10, 20, 30])

In [11]:
a.reshape((1, -1)).T  # -1 infers the size based on the other paramter

array([[10],
       [20],
       [30]])

If the vector had been defined as a 2D array of type `matrix`

In [13]:
b.T

matrix([[10],
        [20],
        [30]])

In [15]:
A = array([[11,12,13], [21,22,23], [31,32,33]])  # Define matrix of size 3x3 as 2D 'array-type'
B = matrix('11 12 13; 21 22 23; 31 32 33')  # Define matrix of size 3x3 as 'matrix-type'

print("A.shape is", A.shape, "and B.shape is", B.shape)

A.shape is (3, 3) and B.shape is (3, 3)


But what happens if you select the first **column** from each?

In [17]:
print(A[:,0])
print(B[:,0])

[11 21 31]
[[11]
 [21]
 [31]]


To make things even more confusing, what happens when I start to do some operations (e.g. multiple)?

In [18]:
a = matrix('4 3; 2 1')
b = matrix('1 2; 3 4')

c = array([[4, 3], [2, 1]])
d = array([[1, 2], [3, 4]])

print(a)
print(c)

[[4 3]
 [2 1]]
[[4 3]
 [2 1]]


In [20]:
print(a*b)
print(c*d)

[[13 20]
 [ 5  8]]
[[4 6]
 [6 4]]


In [22]:
print(a**2)
print(c**2)

[[22 15]
 [10  7]]
[[16  9]
 [ 4  1]]


In [24]:
print(c*b)

[[13 20]
 [ 5  8]]


Note that the types of a and c are different, so it shouldn't be a surprise that they might behave differently

In [26]:
type(a), type(c)

(numpy.matrixlib.defmatrix.matrix, numpy.ndarray)

The main advantage of numpy arrays is that they are more general than 2-dimensional matrices. If you want a 3-dimensional array you'll *need* to use ndarray, not a matrix object.

So, I suggest you stick solely with ndarrays, then you can do everything matrix objects can do, and more. You do have to take care of different notations.

### Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [27]:
v = arange(0, 3)
v

array([0, 1, 2])

In [28]:
v * 2

array([0, 2, 4])

In [29]:
v + 2

array([2, 3, 4])

In [30]:
A = array([[10, 11, 12], [20, 21, 22], [30, 31, 32]])
A * 2

array([[20, 22, 24],
       [40, 42, 44],
       [60, 62, 64]])

In [31]:
A + 2

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

### Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behaviour is **element-wise** operations:

In [32]:
A * A # element-wise multiplication

array([[ 100,  121,  144],
       [ 400,  441,  484],
       [ 900,  961, 1024]])

In [33]:
v * v

array([0, 1, 4])

If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:

In [34]:
A.shape, v.shape

((3, 3), (3,))

In [35]:
A * v

array([[ 0, 11, 24],
       [ 0, 21, 44],
       [ 0, 31, 64]])

### Matrix algebra

What about matrix mutiplication? We use the `dot` function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments: 

In [36]:
dot(A, A)

array([[ 680,  713,  746],
       [1280, 1343, 1406],
       [1880, 1973, 2066]])

In [37]:
dot(A, v)

array([35, 65, 95])

In [38]:
dot(v, v)

5

In [39]:
outer(v,v)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

See also the related functions: `inner`, `outer`, `cross`, `kron`, `tensordot`. Try for example `help(kron)`.

In [40]:
# instead of dot(A,A), we could also do
linalg.matrix_power(A, 2)

array([[ 680,  713,  746],
       [1280, 1343, 1406],
       [1880, 1973, 2066]])

### Array/Matrix transformations

Other mathematical functions that transform matrix objects are:

In [41]:
C = array([[1j, 2j], [3j, 4j]])
C

array([[ 0.+1.j,  0.+2.j],
       [ 0.+3.j,  0.+4.j]])

In [42]:
conjugate(C)

array([[ 0.-1.j,  0.-2.j],
       [ 0.-3.j,  0.-4.j]])

We can extract the real and imaginary parts of complex-valued arrays using `real` and `imag`:

In [43]:
real(C) # same as: C.real

array([[ 0.,  0.],
       [ 0.,  0.]])

In [44]:
imag(C) # same as: C.imag

array([[ 1.,  2.],
       [ 3.,  4.]])

Or the complex argument and absolute value

In [45]:
angle(C+1) # heads up MATLAB Users, angle is used instead of arg

array([[ 0.78539816,  1.10714872],
       [ 1.24904577,  1.32581766]])

In [46]:
abs(C)

array([[ 1.,  2.],
       [ 3.,  4.]])

### Matrix computations

#### Inverse

In [47]:
linalg.inv(C) # equivalent to C.I for matrix type

array([[ 0.+2.j ,  0.-1.j ],
       [ 0.-1.5j,  0.+0.5j]])

In [48]:
linalg.inv(C).dot(C)

array([[  1.00000000e+00+0.j,   0.00000000e+00+0.j],
       [  1.11022302e-16+0.j,   1.00000000e+00+0.j]])

#### Determinant

In [49]:
linalg.det(C)

(2.0000000000000004+0j)

In [50]:
linalg.det(linalg.inv(C))

(0.49999999999999972+0j)

## Solving a linear matrix equation
Let's now solve the linear system from the slide deck
$$ x+y = 27 \\ 2x -y = 0 $$
which we represented with the matrices
$$ \begin{bmatrix} 1 & 1 \\ 2 & -1 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 27 \\ 0 \end{bmatrix}$$

In [51]:
a = array([[1,1], [2,-1]])
b = array([27,0])
x = linalg.solve(a, b)
x

array([  9.,  18.])